# Generated by Django 5.1.5 on 2025-03-02 20:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='The date and time the record was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, db_comment='The date and time the record was last udpated.', verbose_name='Updated At')),
                ('name', models.CharField(db_comment='The name of the Skill.', max_length=100, verbose_name='Name')),
                ('description', models.CharField(db_comment='A detailed description of the Skill.', max_length=254, verbose_name='Description')),
                ('created_by', models.ForeignKey(blank=True, db_comment='The user who created the record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(blank=True, db_comment='The user who last updated the record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='The date and time the record was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, db_comment='The date and time the record was last udpated.', verbose_name='Updated At')),
                ('name', models.CharField(db_comment='The name of the Event.', max_length=100, verbose_name='Name')),
                ('description', models.CharField(db_comment='A detailed description of the Event.', max_length=254, verbose_name='Description')),
                ('location', models.CharField(db_comment='The location of the event.', max_length=254, verbose_name='Location')),
                ('urgency', models.IntegerField(choices=[(4, 'Critical'), (3, 'High'), (2, 'Medium'), (1, 'Low')], db_comment='The urgency of the event.', default=2, verbose_name='Urgency')),
                ('date', models.DateTimeField(blank=True, db_comment='The date and time of the Event.', null=True, verbose_name='Date')),
                ('created_by', models.ForeignKey(blank=True, db_comment='The user who created the record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(blank=True, db_comment='The user who last updated the record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
                ('required_skills', models.ManyToManyField(to='main.skill')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
