# Generated by Django 5.1.5 on 2025-03-02 20:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='The date and time the record was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, db_comment='The date and time the record was last udpated.', verbose_name='Updated At')),
                ('name', models.CharField(help_text='The name of the task.', max_length=254, verbose_name='Name')),
                ('description', models.CharField(help_text='The description of the task.', max_length=254, verbose_name='Description')),
                ('capacity', models.IntegerField(db_comment='The maximum number of Volunteers the Task can hold.', default=-1, verbose_name='Capacity')),
                ('location', models.CharField(blank=True, db_comment='The location of the task.', max_length=254, verbose_name='Location')),
                ('created_by', models.ForeignKey(blank=True, db_comment='The user who created the record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('event', models.ForeignKey(blank=True, help_text='The parent Event record this task is for.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='main.event', verbose_name='Related Event')),
                ('updated_by', models.ForeignKey(blank=True, db_comment='The user who last updated the record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
