# Generated by Django 5.1.5 on 2025-03-02 20:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_event_created_at_alter_event_created_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendeeRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time the record was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time the record was last udpated.', verbose_name='Updated At')),
                ('rating', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4)], help_text='The rating out of 5.', verbose_name='Urgency')),
                ('comments', models.CharField(blank=True, help_text='Comments about the rating.', max_length=254, verbose_name='Comments')),
                ('attendee', models.ForeignKey(blank=True, help_text='The attendee this rating is rating.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendee_ratings', to=settings.AUTH_USER_MODEL, verbose_name='Related Attendee')),
                ('created_by', models.ForeignKey(blank=True, help_text='The user who created the record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('event', models.ForeignKey(blank=True, help_text='The event the attendee atteneded to recieve this rating.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendee_ratings', to='main.event', verbose_name='Related Event')),
                ('updated_by', models.ForeignKey(blank=True, help_text='The user who last updated the record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EventRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time the record was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time the record was last udpated.', verbose_name='Updated At')),
                ('rating', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4)], help_text='The rating out of 5.', verbose_name='Urgency')),
                ('comments', models.CharField(blank=True, help_text='Comments about the rating.', max_length=254, verbose_name='Comments')),
                ('created_by', models.ForeignKey(blank=True, help_text='The user who created the record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('event', models.ForeignKey(blank=True, help_text='The event the attendee atteneded to recieve this rating.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_ratings', to='main.event', verbose_name='Related Event')),
                ('updated_by', models.ForeignKey(blank=True, help_text='The user who last updated the record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time the record was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time the record was last udpated.', verbose_name='Updated At')),
                ('subject', models.CharField(help_text='The subject of the message.', max_length=254, verbose_name='Subject')),
                ('body', models.CharField(blank=True, help_text='The content of the message.', max_length=254, verbose_name='Body')),
                ('created_by', models.ForeignKey(blank=True, help_text='The user who created the record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('event', models.ForeignKey(blank=True, help_text='The parent Event record this notification is for.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='main.event', verbose_name='Related Event')),
                ('updated_by', models.ForeignKey(blank=True, help_text='The user who last updated the record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
