# Generated by Django 5.1.5 on 2025-03-02 21:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_attendeerating_eventrating_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventrating',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='eventrating',
            name='event',
        ),
        migrations.RemoveField(
            model_name='eventrating',
            name='updated_by',
        ),
        migrations.AlterField(
            model_name='event',
            name='required_skills',
            field=models.ManyToManyField(blank=True, null=True, to='main.skill'),
        ),
        migrations.CreateModel(
            name='AttendeeReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time the record was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time the record was last udpated.', verbose_name='Updated At')),
                ('rating', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4)], help_text='The rating out of 5.', verbose_name='Urgency')),
                ('comments', models.CharField(blank=True, help_text='Comments about the review.', max_length=254, verbose_name='Comments')),
                ('attendee', models.ForeignKey(blank=True, help_text='The attendee this review is reviewing.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendee_reviews', to=settings.AUTH_USER_MODEL, verbose_name='Related Attendee')),
                ('created_by', models.ForeignKey(blank=True, help_text='The user who created the record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('event', models.ForeignKey(blank=True, help_text='The event the attendee atteneded to recieve this reviewing.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendee_reviews', to='main.event', verbose_name='Related Event')),
                ('updated_by', models.ForeignKey(blank=True, help_text='The user who last updated the record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EventReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time the record was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time the record was last udpated.', verbose_name='Updated At')),
                ('rating', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4)], help_text='The rating out of 5.', verbose_name='Urgency')),
                ('comments', models.CharField(blank=True, help_text='Comments about the review.', max_length=254, verbose_name='Comments')),
                ('created_by', models.ForeignKey(blank=True, help_text='The user who created the record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('event', models.ForeignKey(blank=True, help_text='The event the attendee atteneded to recieve this review.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_reviews', to='main.event', verbose_name='Related Event')),
                ('updated_by', models.ForeignKey(blank=True, help_text='The user who last updated the record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='AttendeeRating',
        ),
        migrations.DeleteModel(
            name='EventRating',
        ),
    ]
