# Generated by Django 5.1.5 on 2025-03-02 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_eventrating_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendeereview',
            name='rating',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], help_text='The rating out of 5.', verbose_name='Rating'),
        ),
        migrations.AlterField(
            model_name='eventreview',
            name='rating',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], help_text='The rating out of 5.', verbose_name='Rating'),
        ),
    ]
