# Generated by Django 5.1.5 on 2025-03-04 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_attendeereview_rating_alter_eventreview_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='required_skills',
            field=models.ManyToManyField(blank=True, to='main.skill'),
        ),
    ]
