# Generated by Django 5.1.5 on 2025-03-19 21:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_event_required_skills'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='John Doe', max_length=100)),
                ('address1', models.CharField(default='123 Main St', max_length=255)),
                ('address2', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(default='New York', max_length=100)),
                ('state', models.CharField(default='NY', max_length=2)),
                ('zipcode', models.CharField(default='11223', max_length=10)),
                ('preferences', models.TextField(blank=True, null=True)),
                ('start_availability', models.DateField(blank=True, null=True)),
                ('end_availability', models.DateField(blank=True, null=True)),
                ('skills', models.ManyToManyField(blank=True, to='main.skill')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
