# Generated by Django 5.1.5 on 2025-03-21 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_rename_required_skills_event_skills_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='skills',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='updated_by',
        ),
        migrations.AddField(
            model_name='event',
            name='required_skills',
            field=models.ManyToManyField(blank=True, to='main.skill'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(default='1234567890', max_length=15),
        ),
    ]
