# Generated by Django 5.1.5 on 2025-04-20 18:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_userprofile_address1_alter_userprofile_city_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='admin',
            field=models.ForeignKey(blank=True, help_text='The admin who is in charge of the Event.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_events', to=settings.AUTH_USER_MODEL, verbose_name='Event Admin'),
        ),
    ]
