# Generated by Django 5.1.5 on 2025-04-20 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_event_attendees'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='event',
            name='attendees',
        ),
        migrations.RemoveField(
            model_name='task',
            name='attendees',
        ),
    ]
