# Generated by Django 5.1.5 on 2025-04-20 23:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_avataroption'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.ForeignKey(blank=True, help_text='The avatar selected by the user.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='main.avataroption', verbose_name='Avatar'),
        ),
    ]
