# Generated by Django 5.1.5 on 2025-04-22 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_event_admin_event_attendees_notification_is_read_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='body',
            field=models.TextField(blank=True, help_text='The content of the message.', max_length=254, verbose_name='Body'),
        ),
    ]
