# Generated by Django 5.1.5 on 2025-04-22 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_alter_event_description_alter_skill_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='email',
        ),
    ]
